name: Run Monthly Energy Consumption Report

# Schedule to run at 18:30 UTC, which is equivalent to 00:00 IST on the 1st day of each month
on:
  schedule:
    - cron: "30 18 1 * *"  # Runs on the 1st of every month at 18:30 UTC, which is 00:00 IST

  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-monthly-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use the version your script requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your dependencies are listed here

    - name: Run the Python script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: python monthly_report.py  # Replace with the actual name of your script file
